

trigger:
- main

pool:
  name: NayaInfra

variables:
  workingDir: '$(System.DefaultWorkingDirectory)/environment/Dev'
  tflintVersion: '0.53.0'
  tfsecVersion: '1.28.10'

stages:
#==============================================================
# Stage-1 Validation & Security Scan
#==============================================================
- stage: Validation
  displayName: "Terraform Validation & Security"
  jobs:
  - job: Validate
    displayName: "Terraform Checks"
    steps:
    # Terraform Install
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.10.5'

    # Terraform Init
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(workingDir)'
        backendServiceArm: 'NayaInfra'
        backendAzureRmStorageAccountName: 'gssstrg'
