trigger:
- main

pool:
  name: NayaInfra

variables:
  serviceConnection: 'NayaInfra'
  backendStorageAccount: 'gssstrg'
  backendContainer: 'gsscontainer'

##############################################
# DEV
##############################################

stages:

- stage: Dev
  displayName: DEV

  jobs:

  - job: TerraformDev

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - powershell: |
        terraform version
        where tflint
        tflint --version
        where tfsec
        tfsec --version
        where checkov
        checkov --version
      displayName: Verify Installed Tools

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: azurerm
        command: init
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Dev'
        backendServiceArm: '$(serviceConnection)'
        backendAzureRmStorageAccountName: '$(backendStorageAccount)'
        backendAzureRmContainerName: '$(backendContainer)'
        backendAzureRmKey: 'dev.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Dev'

    - powershell: |
        tflint --init
        tflint
      displayName: TFLint
      workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Dev'

    - powershell: |
        tfsec .
      displayName: TFSEC
      workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Dev'

    - powershell: |
        checkov -d .
      displayName: Checkov
      workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Dev'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Dev'
        environmentServiceNameAzureRM: '$(serviceConnection)'

##############################################
# QA
##############################################

- stage: QA
  dependsOn: Dev
  displayName: QA

  jobs:

  - job: TerraformQA

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - powershell: |
        terraform version
        where tflint
        tflint --version
        where tfsec
        tfsec --version
        where checkov
        checkov --version
      displayName: Verify Installed Tools

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: azurerm
        command: init
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Qa'
        backendServiceArm: '$(serviceConnection)'
        backendAzureRmStorageAccountName: '$(backendStorageAccount)'
        backendAzureRmContainerName: '$(backendContainer)'
        backendAzureRmKey: 'qa.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Qa'

    - powershell: |
        tflint --init
        tflint
      displayName: TFLint
      workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Qa'

    - powershell: |
        tfsec .
      displayName: TFSEC
      workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Qa'

    - powershell: |
        checkov -d .
      displayName: Checkov
      workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Qa'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Qa'
        environmentServiceNameAzureRM: '$(serviceConnection)'

##############################################
# PROD
##############################################

- stage: Prod
  dependsOn: QA
  displayName: PROD

  jobs:

  - job: TerraformProd

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - powershell: |
        terraform version
        where tflint
        tflint --version
        where tfsec
        tfsec --version
        where checkov
        checkov --version
      displayName: Verify Installed Tools

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: azurerm
        command: init
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Prod'
        backendServiceArm: '$(serviceConnection)'
        backendAzureRmStorageAccountName: '$(backendStorageAccount)'
        backendAzureRmContainerName: '$(backendContainer)'
        backendAzureRmKey: 'prod.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Prod'

    - powershell: |
        tflint --init
        tflint
      displayName: TFLint
      workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Prod'

    - powershell: |
        tfsec .
      displayName: TFSEC
      workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Prod'

    - powershell: |
        checkov -d .
      displayName: Checkov
      workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Prod'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Prod'
        environmentServiceNameAzureRM: '$(serviceConnection)'