

# azure-pipelines.yml
trigger:
  - main

resources:
  repositories: []

variables:
  azureSubscription: 'NayaInfra'                  # Azure RM Service Connection
  acrServiceConnection: 'a0705b5b-e8b4-4c9e-802a-eca3dae3f3e0'
  acrName: 'gssdevacr'
  containerRegistry: 'gssdevacr.azurecr.io'
  imageRepository: 'gaurvssrisnayainfra'
  dockerfilePath: '$(Build.SourcesDirectory)/independence-day-app/Dockerfile'
  tag: '$(Build.BuildId)'
  resourceGroup: 'RG-Dev'
  containerGroup: 'independence-day-app'
  dnsNameLabel: 'independence-day-demo-$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest

stages:

  #=====================================================
  # Stage-1 : Security Scan
  #=====================================================
  - stage: SecurityScan
    displayName: "Security Scan"
    jobs:
      - job: Trivy
        steps:
          - checkout: self

          - script: |
              sudo apt-get update
              sudo apt-get install -y wget

              TRIVY_VERSION=0.73.0

              wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.deb

              sudo dpkg -i trivy_${TRIVY_VERSION}_Linux-64bit.deb

              trivy --version
            displayName: Install Trivy

          - script: |
              trivy fs \
                --exit-code 1 \
                --severity CRITICAL,HIGH \
                .
            displayName: Scan Source Code

  #=====================================================
  # Stage-2 : Docker Build & Push
  #=====================================================
  - stage: Build
    dependsOn: SecurityScan
    jobs:
      - job: Docker
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Docker Build and Push
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(acrServiceConnection)
              tags: |
                $(tag)
                latest

  #=====================================================
  # Stage-3 : Production Approval
  #=====================================================
  - stage: Approval
    dependsOn: Build
    jobs:
      - deployment: WaitForApproval
        displayName: Manual Approval
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Approved Successfully"

  #=====================================================
  # Stage-4 : Deploy Container
  #=====================================================
  - stage: Deploy
    dependsOn: Approval
    jobs:
      - job: DeployACI
        steps:
          - task: AzureCLI@2
            displayName: Deploy Azure Container Instance
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az container delete \
                  --resource-group $(resourceGroup) \
                  --name $(containerGroup) \
                  --yes || true

                az container create \
                  --resource-group $(resourceGroup) \
                  --name $(containerGroup) \
                  --image $(containerRegistry)/$(imageRepository):$(tag) \
                  --registry-login-server $(containerRegistry) \
                  --registry-username $(acrName) \
                  --registry-password $(az acr credential show --name $(acrName) --query passwords[0].value -o tsv) \
                  --dns-name-label $(dnsNameLabel) \
                  --ports 80 \
                  --os-type Linux \
                  --cpu 1 \
                  --memory 1.5

                echo "Application URL"

                az container show \
                  --resource-group $(resourceGroup) \
                  --name $(containerGroup) \
                  --query ipAddress.fqdn \
                  -o tsv
