apiVersion: apps/v1
kind: Deployment

metadata:
  name: saawan
  namespace: {{ .Values.namespace }}

  labels:
    app: saawan

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: saawan

  template:
    metadata:
      labels:
        app: saawan

    spec:

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
      {{- end }}
      {{- end }}

      containers:
        - name: saawan

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}

            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10

      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}

      affinity:
{{ toYaml .Values.affinity | indent 8 }}

      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}